openapi: 3.0.0
info:
  title: QnA API
  version: 0.1.0
  description: The APi for the QnA chatbost service
  contact:
    name: QnA
    url: group37example.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://example.com/api
    description: API server
paths:
  /documents:
    get:
      summary: Get all documents
      operationId: getAllDocuments
      tags:
        - documents
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Document'
        '400':
          description: The request is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The requested resource could not be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post: 
      summary: Create a document
      operationId: createDocument
      tags:
        - documents
      requestBody:
        description: The document to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '201':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: The request is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The requested resource could not be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch: 
      summary: Update a document
      operationId: updateDocument
      tags:
        - documents
      requestBody:
        description: The document to update
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Document'
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: The request is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The requested resource could not be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /documents/{id}:
    get:
      summary: Get a document
      operationId: getDocument
      tags:
        - documents
      parameters:
        - name: id
          in: path
          description: The ID of the document to retrieve
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Document'
        '400':
          description: The request is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The document was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a document
      operationId: deleteDocument
      tags:
        - documents
      parameters:
        - name: id
          in: path
          description: The id of the document to delete
          required: true
          schema:
            type: string
      responses:
        '204':
          description: A successful response
        '400':
          description: The request is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The requested resource could not be found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: An unexpected error occurred
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /questions:
    post:
      summary: Ask a question
      operationId: askQuestion
      tags:
        - questions
      requestBody:
        description: The question to ask
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
      responses:
        '201':
          description: A successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '400':
          description: The request is invalid
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The document was not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: The server encountered an error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error: 
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    Document:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    Question:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
        documentId:
          type: string
        document:
          $ref: '#/components/schemas/Document'
    


